# nix
if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then 
  . $HOME/.nix-profile/etc/profile.d/nix.sh; 
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f $HOME/.config/p10k.zsh ]] || source $HOME/.config/p10k.zsh

# only put cwd on tab/window title
export DISABLE_AUTO_TITLE="true"
precmd () {print -Pn "\e]0;%~\a"}

# brolang config
export GO111MODULE="on"
# set these explicitly so they are available to shell scripts
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
# add go binaries to my path
export PATH="$PATH:$GOBIN" 
# add user controlled bin directory to my path
export PATH="$PATH:$HOME/bin"
